version: "3"

services:
  booking-ticket-db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - booking-ticket-network

volumes:
  pgdata:

networks:
  booking-ticket-network:
    driver: bridge
