import psycopg2
import json

# Connect to your PostgreSQL database
conn = psycopg2.connect(
    dbname="booking_ticket",
    user="admin",
    password="admin",
    host="localhost",
    port="5005",
)

# Create a cursor object to execute SQL queries
cur = conn.cursor()

# Load the JSON data
data = [
    {
        "id": 1,
        "name": "Spring",
        "seats": [
            {"id": 1, "number": 1, "isBooked": False},
            {"id": 2, "number": 2, "isBooked": False},
            {"id": 3, "number": 3, "isBooked": False},
            {"id": 4, "number": 4, "isBooked": False},
            {"id": 5, "number": 5, "isBooked": False},
            {"id": 6, "number": 6, "isBooked": False},
            {"id": 7, "number": 7, "isBooked": False},
            {"id": 8, "number": 8, "isBooked": False},
            {"id": 9, "number": 9, "isBooked": False},
            {"id": 10, "number": 10, "isBooked": False},
            {"id": 11, "number": 11, "isBooked": False},
            {"id": 12, "number": 12, "isBooked": False},
            {"id": 13, "number": 13, "isBooked": False},
            {"id": 14, "number": 14, "isBooked": False},
            {"id": 15, "number": 15, "isBooked": False},
            {"id": 16, "number": 16, "isBooked": False},
            {"id": 17, "number": 17, "isBooked": False},
            {"id": 18, "number": 18, "isBooked": False},
            {"id": 19, "number": 19, "isBooked": False},
            {"id": 20, "number": 20, "isBooked": False},
            {"id": 21, "number": 21, "isBooked": False},
            {"id": 22, "number": 22, "isBooked": False},
            {"id": 23, "number": 23, "isBooked": False},
            {"id": 24, "number": 24, "isBooked": False},
            {"id": 25, "number": 25, "isBooked": False},
            {"id": 26, "number": 26, "isBooked": False},
            {"id": 27, "number": 27, "isBooked": False},
            {"id": 28, "number": 28, "isBooked": False},
            {"id": 29, "number": 29, "isBooked": False},
            {"id": 30, "number": 30, "isBooked": False},
            {"id": 31, "number": 31, "isBooked": False},
            {"id": 32, "number": 32, "isBooked": False},
            {"id": 33, "number": 33, "isBooked": False},
            {"id": 34, "number": 34, "isBooked": False},
            {"id": 35, "number": 35, "isBooked": False},
            {"id": 36, "number": 36, "isBooked": False},
            {"id": 37, "number": 37, "isBooked": False},
            {"id": 38, "number": 38, "isBooked": False},
            {"id": 39, "number": 39, "isBooked": False},
            {"id": 40, "number": 40, "isBooked": False},
            {"id": 41, "number": 41, "isBooked": False},
            {"id": 42, "number": 42, "isBooked": False},
            {"id": 43, "number": 43, "isBooked": False},
            {"id": 44, "number": 44, "isBooked": False},
            {"id": 45, "number": 45, "isBooked": False},
        ],
    },
    {
        "id": 2,
        "name": "Summer",
        "seats": [
            {"id": 46, "number": 1, "isBooked": False},
            {"id": 47, "number": 2, "isBooked": False},
            {"id": 48, "number": 3, "isBooked": False},
            {"id": 49, "number": 4, "isBooked": False},
            {"id": 50, "number": 5, "isBooked": False},
            {"id": 51, "number": 6, "isBooked": False},
            {"id": 52, "number": 7, "isBooked": False},
            {"id": 53, "number": 8, "isBooked": False},
            {"id": 54, "number": 9, "isBooked": False},
            {"id": 55, "number": 10, "isBooked": False},
            {"id": 56, "number": 11, "isBooked": False},
            {"id": 57, "number": 12, "isBooked": False},
            {"id": 58, "number": 13, "isBooked": False},
            {"id": 59, "number": 14, "isBooked": False},
            {"id": 60, "number": 15, "isBooked": False},
            {"id": 61, "number": 16, "isBooked": False},
            {"id": 62, "number": 17, "isBooked": False},
            {"id": 63, "number": 18, "isBooked": False},
            {"id": 64, "number": 19, "isBooked": False},
            {"id": 65, "number": 20, "isBooked": False},
            {"id": 66, "number": 21, "isBooked": False},
            {"id": 67, "number": 22, "isBooked": False},
            {"id": 68, "number": 23, "isBooked": False},
            {"id": 69, "number": 24, "isBooked": False},
            {"id": 70, "number": 25, "isBooked": False},
            {"id": 71, "number": 26, "isBooked": False},
            {"id": 72, "number": 27, "isBooked": False},
            {"id": 73, "number": 28, "isBooked": False},
            {"id": 74, "number": 29, "isBooked": False},
            {"id": 75, "number": 30, "isBooked": False},
            {"id": 76, "number": 31, "isBooked": False},
            {"id": 77, "number": 32, "isBooked": False},
            {"id": 78, "number": 33, "isBooked": False},
            {"id": 79, "number": 34, "isBooked": False},
            {"id": 80, "number": 35, "isBooked": False},
            {"id": 81, "number": 36, "isBooked": False},
            {"id": 82, "number": 37, "isBooked": False},
            {"id": 83, "number": 38, "isBooked": False},
            {"id": 84, "number": 39, "isBooked": False},
            {"id": 85, "number": 40, "isBooked": False},
            {"id": 86, "number": 41, "isBooked": False},
            {"id": 87, "number": 42, "isBooked": False},
            {"id": 88, "number": 43, "isBooked": False},
            {"id": 89, "number": 44, "isBooked": False},
            {"id": 90, "number": 45, "isBooked": False},
        ],
    },
    {
        "id": 3,
        "name": "Fall",
        "seats": [
            {"id": 91, "number": 1, "isBooked": False},
            {"id": 92, "number": 2, "isBooked": False},
            {"id": 93, "number": 3, "isBooked": False},
            {"id": 94, "number": 4, "isBooked": False},
            {"id": 95, "number": 5, "isBooked": False},
            {"id": 96, "number": 6, "isBooked": False},
            {"id": 97, "number": 7, "isBooked": False},
            {"id": 98, "number": 8, "isBooked": False},
            {"id": 99, "number": 9, "isBooked": False},
            {"id": 100, "number": 10, "isBooked": False},
            {"id": 101, "number": 11, "isBooked": False},
            {"id": 102, "number": 12, "isBooked": False},
            {"id": 103, "number": 13, "isBooked": False},
            {"id": 104, "number": 14, "isBooked": False},
            {"id": 105, "number": 15, "isBooked": False},
            {"id": 106, "number": 16, "isBooked": False},
            {"id": 107, "number": 17, "isBooked": False},
            {"id": 108, "number": 18, "isBooked": False},
            {"id": 109, "number": 19, "isBooked": False},
            {"id": 110, "number": 20, "isBooked": False},
            {"id": 111, "number": 21, "isBooked": False},
            {"id": 112, "number": 22, "isBooked": False},
            {"id": 113, "number": 23, "isBooked": False},
            {"id": 114, "number": 24, "isBooked": False},
            {"id": 115, "number": 25, "isBooked": False},
            {"id": 116, "number": 26, "isBooked": False},
            {"id": 117, "number": 27, "isBooked": False},
            {"id": 118, "number": 28, "isBooked": False},
            {"id": 119, "number": 29, "isBooked": False},
            {"id": 120, "number": 30, "isBooked": False},
            {"id": 121, "number": 31, "isBooked": False},
            {"id": 122, "number": 32, "isBooked": False},
            {"id": 123, "number": 33, "isBooked": False},
            {"id": 124, "number": 34, "isBooked": False},
            {"id": 125, "number": 35, "isBooked": False},
            {"id": 126, "number": 36, "isBooked": False},
            {"id": 127, "number": 37, "isBooked": False},
            {"id": 128, "number": 38, "isBooked": False},
            {"id": 129, "number": 39, "isBooked": False},
            {"id": 130, "number": 40, "isBooked": False},
            {"id": 131, "number": 41, "isBooked": False},
            {"id": 132, "number": 42, "isBooked": False},
            {"id": 133, "number": 43, "isBooked": False},
            {"id": 134, "number": 44, "isBooked": False},
            {"id": 135, "number": 45, "isBooked": False},
        ],
    },
    {
        "id": 4,
        "name": "Winter",
        "seats": [
            {"id": 136, "number": 1, "isBooked": False},
            {"id": 137, "number": 2, "isBooked": False},
            {"id": 138, "number": 3, "isBooked": False},
            {"id": 139, "number": 4, "isBooked": False},
            {"id": 140, "number": 5, "isBooked": False},
            {"id": 141, "number": 6, "isBooked": False},
            {"id": 142, "number": 7, "isBooked": False},
            {"id": 143, "number": 8, "isBooked": False},
            {"id": 144, "number": 9, "isBooked": False},
            {"id": 145, "number": 10, "isBooked": False},
            {"id": 146, "number": 11, "isBooked": False},
            {"id": 147, "number": 12, "isBooked": False},
            {"id": 148, "number": 13, "isBooked": False},
            {"id": 149, "number": 14, "isBooked": False},
            {"id": 150, "number": 15, "isBooked": False},
            {"id": 151, "number": 16, "isBooked": False},
            {"id": 152, "number": 17, "isBooked": False},
            {"id": 153, "number": 18, "isBooked": False},
            {"id": 154, "number": 19, "isBooked": False},
            {"id": 155, "number": 20, "isBooked": False},
            {"id": 156, "number": 21, "isBooked": False},
            {"id": 157, "number": 22, "isBooked": False},
            {"id": 158, "number": 23, "isBooked": False},
            {"id": 159, "number": 24, "isBooked": False},
            {"id": 160, "number": 25, "isBooked": False},
            {"id": 161, "number": 26, "isBooked": False},
            {"id": 162, "number": 27, "isBooked": False},
            {"id": 163, "number": 28, "isBooked": False},
            {"id": 164, "number": 29, "isBooked": False},
            {"id": 165, "number": 30, "isBooked": False},
            {"id": 166, "number": 31, "isBooked": False},
            {"id": 167, "number": 32, "isBooked": False},
            {"id": 168, "number": 33, "isBooked": False},
            {"id": 169, "number": 34, "isBooked": False},
            {"id": 170, "number": 35, "isBooked": False},
            {"id": 171, "number": 36, "isBooked": False},
            {"id": 172, "number": 37, "isBooked": False},
            {"id": 173, "number": 38, "isBooked": False},
            {"id": 174, "number": 39, "isBooked": False},
            {"id": 175, "number": 40, "isBooked": False},
            {"id": 176, "number": 41, "isBooked": False},
            {"id": 177, "number": 42, "isBooked": False},
            {"id": 178, "number": 43, "isBooked": False},
            {"id": 179, "number": 44, "isBooked": False},
            {"id": 180, "number": 45, "isBooked": False},
        ],
    },
]

# Iterate through each season and seat data and insert into the database
for season in data:
    season_id = season["id"]
    season_name = season["name"]

    # Insert season data
    cur.execute(
        "INSERT INTO seasons (id, name) VALUES (%s, %s)", (season_id, season_name)
    )

    # Insert seat data for the season
    for seat in season["seats"]:
        seat_id = seat["id"]
        seat_number = seat["number"]
        is_booked = seat["isBooked"]

        cur.execute(
            "INSERT INTO seats (id, season_id, seat_number, is_booked) VALUES (%s, %s, %s, %s)",
            (seat_id, season_id, seat_number, is_booked),
        )

# Commit the changes and close the connection
conn.commit()
conn.close()
